# disable host numeric IP rule
SecRuleRemoveById 920350

# query param
SecRuleUpdateTargetById 930120 "!ARGS:code_verifier"
SecRuleUpdateTargetById 930120 "!ARGS:code_challenge"
SecRuleUpdateTargetById 930120 "!ARGS:state"
SecRuleUpdateTargetById 930120 "!ARGS:nonce"
SecRuleUpdateTargetById 930120 "!ARGS:ext_csrf_state"
SecRuleUpdateTargetById 930120 "!ARGS:csrf_token"
SecRuleUpdateTargetById 930120 "!ARGS:flow_id"
SecRuleUpdateTargetById 930120 "!ARGS:scope"